name: Service Consolidado - CI/CD

on:
  push:
    paths:
      - "src/Services/Consolidado/**"
      - "src/BuildingBlocks/**"
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.0.x"

    - name: Restore
      run: dotnet restore FluxoCaixa.sln

    - name: Build
      run: dotnet build src/Services/Consolidado/FluxoCaixa.Consolidado.API/FluxoCaixa.Consolidado.API.csproj -c Release --no-restore

    - name: Run Consolidado Tests
      run: dotnet test ./tests/FluxoCaixa.Consolidado.Tests --no-build --verbosity normal

    - name: Publish
      run: dotnet publish src/Services/Consolidado/FluxoCaixa.Consolidado.API/FluxoCaixa.Consolidado.API.csproj -c Release -o ./publish-consolidado

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: service-consolidado-artifact
        path: ./publish-consolidado

    - name: Deploy Service Consolidado
      run: |
        echo "TODO: deploy do servi√ßo Consolidado"
